fips_mapping = {
    'Alabama':'01',
    'Alaska':'02',
    'American Samoa':'60',
    'Arizona':'04',
    'Arkansas':'05',
    'California':'06',
    'Colorado':'08',
    'Connecticut':'09',
    'Delaware':'10',
    'Florida':'12',
    'Georgia':'12',
    'Guam':'66',
    'Hawaii':'15',
    'Idaho':'16',
    'Illinois':'17',
    'Indiana':'18',
    'Iowa':'19',
    'Kansas':'20',
    'Kentucky':'21',
    'Louisiana':'22',
    'Maine':'23',
    'Maryland':'24',
    'Massachusetts':'25',
    'Michigan':'26',
    'Minnesota':'27',
    'Mississippi':'28',
    'Missouri':'29',
    'Montana':'30',
    'Nebraska':'31',
    'Nevada':'32',
    'New Hampshire':'33',
    'New Jersey':'34',
    'New Mexico':'35',
    'New York':'36',
    'North Carolina':'37',
    'North Dakota':'38',
    'Northern Mariana Islands':'69',
    'Ohio':'39',
    'Oklahoma':'40',
    'Oregon':'41',
    'Pennsylvania':'42',
    'Puerto Rico':'72',
    'Rhode Island':'44',
    'South Carolina':'45',
    'South Dakota':'46',
    'Tennessee':'47',
    'Texas':'48',
    'Utah':'49',
    'Vermont':'50',
    'Virgin Islands (U.S.)':'78',
    'Virginia':'51',
    'Washington':'53',
    'Washington, District of Columbia':'11',
    'West Virginia':'54',
    'Wisconsin':'55',
    'Wyoming':'56'
}
